apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  rules:
  -  http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rollout-bluegreen-active
              port:
                number: 80
